openapi: 3.0.3

info:
  title: Eclipse Kapua REST API - Device Management - Package
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths: {}

components:
  schemas:
    bundleInfo:
      type: object
      properties:
        name:
          type: string
          description: The bundle name
        version:
          type: string
          description: the bundle version
    devicePackage:
      type: object
      description: A Device Package
      properties:
        name:
          type: string
          description: The name of the package
        version:
          type: string
          description: The version of the package
        bundleInfos:
          type: object
          description: The bundles of this package
          properties:
            bundleInfo:
              type: array
              items:
                $ref: '#/components/schemas/bundleInfo'
        installDate:
          type: string
          description: The installation date of the package
          format: 'date-time'
      example:
        name: org.eclipse.kura.demo.heater
        version: 1.0.300
        bundleInfos:
          bundleInfo:
            - name: org.eclipse.kura.demo.heater
              version: 1.0.300
    devicePackages:
      type: object
      properties:
        devicePackage:
          type: array
          items:
            $ref: '#/components/schemas/devicePackage'
      example:
        type: devicePackages
        devicePackage:
          - name: org.eclipse.kura.demo.heater
            version: 1.0.300
            bundleInfos:
              bundleInfo:
                - name: org.eclipse.kura.demo.heater
                  version: 1.0.300
    devicePackageDownloadRequestFileType:
      type: string
      description: The type of the URI resource content
      enum:
        - DEPLOYMENT_PACKAGE
        - EXECUTABLE_SCRIPT
    devicePackageDownloadRequest:
      type: object
      properties:
        uri:
          type: string
          description: The URI to download the resource
        name:
          type: string
          description: The name of the downloaded package
        version:
          type: string
          description: The version of the downloaded package
        username:
          type: string
          description: The username to use in the HTTP basic authentication when accessing the URI resource
        password:
          type: string
          description: The password to use in the HTTP basic authentication when accessing the URI resource
        fileHash:
          type: string
          description: The MD5 has to check resource integrity after download
        fileType:
          $ref: '#/components/schemas/devicePackageDownloadRequestFileType'
        install:
          type: boolean
          description: Whether to install or not the package after download
        reboot:
          type: boolean
          description: Whether to reboot the device after installation of the package
        rebootDelay:
          type: integer
          description: The delay in milliseconds to delay the reboot after installation
        advancedOptions:
          type: object
          properties:
            restart:
              type: boolean
              description: Whether or not to resume the partial download of the URI resource. The resource is identified by name and version provided
            blockSize:
              type: integer
              description: The block size in kBi to use while downloading the URI resource
            blockDelay:
              type: integer
              description: The delay in ms to delay each block download of the URI resource
            blockTimeout:
              type: integer
              description: The delay timeout to download each block of the URI resource
            notifyBlockSize:
              type: integer
              description: The amount of kBi to download before sending a new Operation Notification to the platform
            installVerifierURI:
              type: string
              description: The URI to download the script that can verify that the package installation has successfully completed.
      required:
        - uri
        - name
        - version
      example:
        uri: https://download.eclipse.org/kura/releases/4.1.0/org.eclipse.kura.demo.heater_1.0.500.dp
        name: heater
        version: 1.0.500
        username: username
        password: password
        fileHash: MD5:0d04154164145cd6b2167fdd457ed28f
        fileType: DEPLOYMENT_PACKAGE
        install: true
        reboot: false
        rebootDelay: 0
        advancedOptions:
          restart: false
          blockSize: 128
          blockDelay: 0
          blockTimeout: 5000
          notifyBlockSize: 256
          installVerifierURI: https://download.eclipse.org/kura/releases/4.1.0/org.eclipse.kura.demo.heater_1.0.500.verifier.sh
    devicePackageUninstallRequest:
      type: object
      properties:
        name:
          type: string
          description: The package name to uninstall
        version:
          type: string
          description: The package verson to uninstall
        reboot:
          type: boolean
          description: Whether to reboot the device after uninstall of the package
        rebootDelay:
          type: integer
          description: The delay in milliseconds to delay the reboot after uninstallation
      required:
        - name
        - version
      example:
        name: org.eclipse.kura.demo.heater
        version: 1.0.500
        reboot: false
        rebootDelay: 0
